apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sera-node-modules-pvc
  namespace: sera-namespace # Replace with your namespace if needed
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sera-models-pvc
  namespace: sera-namespace # Replace with your namespace if needed
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sera-mongodb-pvc
  namespace: sera-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sera-lua-scripts-pvc
  namespace: sera-namespace # Replace with your namespace if needed
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
