version: '3.7'

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      # - node_modules:/workspace/node_modules
    command: tail -f /dev/null  # Keeps the container running

# volumes:
#   node_modules:
#     name: node_modules