version: '3.8'
services:
  sera:
    build:
      context: .
    volumes:
      - .:/workspace
    environment:
      DOMAIN_NAME: "example.sera"
      BE_ROUTER_PORT: "12000"
      FE_CATALOG_PORT: "12010"
      BE_BUILDER_PORT: "12030"
      BE_SOCKET_PORT: "12040"
      BE_SEQUENCER_PORT: "12050"
      GITHUB_TOKEN: "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"
    ports:
      - "12010:12010"
      - "12030:12030"
      - "12040:12040"
      - "12000:12000"
      - "12050:12050"
    networks:
      - sera_internal_network
    extra_hosts:
      - "local.sera:127.0.0.1"
      - "manage.sera:127.0.0.1"
      - "test.sera:127.0.0.1"
      - "dns.sera:127.0.0.1"