version: '3.8'
services:
  mongo:
    build:
      context: ./sera-db-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"