version: '3.7'

services:

  frontend_catalog:
    image: frontend_catalog
    build:
      context: ../fe_Catalog
      dockerfile: Dockerfile
    depends_on:
      - workspace

  backend_builder:
    image: backend_builder
    build:
      context: ../be_Builder
      dockerfile: Dockerfile
    volumes:
      - node_modules:/workspace/node_modules
    depends_on:
      - workspace

  backend_socket:
    image: backend_socket
    build:
      context: ../be_Socket
      dockerfile: Dockerfile
    volumes:
      - node_modules:/workspace/node_modules
    depends_on:
      - workspace

  backend_sequencer:
    image: backend_sequencer
    build:
      context: ../be_Sequencer
      dockerfile: Dockerfile
    volumes:
      - node_modules:/workspace/node_modules
    depends_on:
      - workspace

  backend_processor:
    image: backend_processor
    build:
      context: ../be_Processor
      dockerfile: Dockerfile
    volumes:
      - node_modules:/workspace/node_modules
    depends_on:
      - workspace

volumes:
  node_modules:
    external: true