apiVersion: v1
kind: Pod
metadata:
  name: temp-debug-pod
spec:
  containers:
    - name: debug-container
      image: curlimages/curl:latest
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: sera-node-modules
          mountPath: /mnt/node_modules
    - name: debug-busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: sera-node-modules
          mountPath: /mnt/node_modules
  volumes:
    - name: sera-node-modules
      persistentVolumeClaim:
        claimName: sera-node-modules-pvc
  restartPolicy: Never
