name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Set this to the branch you want to build from

env:
  IMAGE_NAME: ${{ github.repository }}  # Use the GitHub repository name as the image name

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out your repository under $GITHUB_WORKSPACE

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Sets up Docker Buildx to build multi-platform images

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=ref,event=branch

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Output image digest
        run: echo "The image's digest is ${{ steps.build-and-push.outputs.digest }}"
