name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Set the branch to your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.ACTIONS_IMAGE_SECRET }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./.devcontainer/Dockerfile
        push: true
        tags: ghcr.io/sera-ai/sera-development:latest
